### ISSUE TITLE
Simulate Guan_2015

### ISSUE THREAD

**Issue by fkalholm** [nbassler/PubSim#10]
@grzanka , could you help me simulate the protons for the Guan data? You can generate the files by running "mcscripter config_H.cfg" in the "/PubSim/2015_Guan/sim-files"-folder.
I dont know how many particles you used last time, but a similar, or even slightly smaller amount would probably be ok.

**Comment by grzanka** [comment]
Do we wait for new version of shieldhit or the config files were updated to accomodate for "neutron problem" ?

**Comment by fkalholm** [comment]
I have now added a filter so only particles with z>0 are counted. Would not that have the same effect, do we don't have to wait?
Cheers
Fredrik



Sent from my Galaxy



-------- Original message --------
From: Leszek Grzanka ***@***.***>
Date: 5/14/21 16:09 (GMT+01:00)
To: nbassler/PubSim ***@***.***>
Cc: Fredrik Kalholm ***@***.***>, Author ***@***.***>
Subject: Re: [nbassler/PubSim] Simulate Guan_2015 (#10)


Do we wait for new version of shieldhit or the config files were updated to accomodate for "neutron problem" ?
