### ISSUE TITLE
run simultions

### ISSUE THREAD

**Issue by fkalholm** [nbassler/PubSim#17]
@grzanka can you help me run sims of all four proton combinations (PSTAR/ICRU and Water/Tissue). Create the sim-files by running the four cfg-files with mcscripter under PubSim/sim-files: "config_H_Water_ICRU.cfg", "config_H_Tissue_ICRU.cfg", "config_H_Water_PSTAR.cfg" and "config_H_Tissue_PSTAR.cfg"

**Comment by grzanka** [comment]
[output.pdf](https://github.com/nbassler/PubSim/files/7711420/output.pdf)
[output.csv](https://github.com/nbassler/PubSim/files/7711423/output.csv)



@fkalholm, can you check these results ?

**Comment by fkalholm** [comment]
It looks good. One small issue is that the columns for dose and track averaged zeff2/beta2 are swapped (dose should come first, and track last, but it is the other way around). Easy to change manually though!
